#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Write the dated open-item digest file (read-only product: local markdown, nothing outward).

Reads two annotated candidate files from the working folder (everything collected, and the subset
that is new since the last run) and writes `digest-<YYYY-MM-DD>.md` there. An existing file for the
same date is never overwritten: a `-2`, `-3` suffix is used. The file lists source references and
titles, never full text. It does not consult Linear (intake re-asks approval on every read, which an
unattended run cannot give), so "new" means "not seen in an earlier digest".

Usage (run inside the repository; names are plain files in the working folder). Each of the first
two
arguments is a comma-separated list of file names, one per source that was collected:
  wlgr_digest.py <annotated-a.json,annotated-b.json,...> <new-a.json,new-b.json,...>
                 [--first-run] [--failed reports,issues,prs]
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import wlgr_paths  # noqa: E402

SOURCES = {"report": "Reports", "github-issue": "GitHub issues", "pull-request": "Pull requests"}
FAILABLE = {"reports", "issues", "prs"}


def _line(text: str) -> str:
    """One markdown-safe line from collected text."""
    return " ".join(str(text).split()).replace("|", "/")[:200]


def build_digest(
    annotated: list[dict], new: list[dict], today: str, first_run: bool, failed: list[str]
) -> str:
    collected, fresh, ambiguous = Counter(), Counter(), Counter()
    for c in annotated:
        collected[c["source"]] += 1
    for c in new:
        fresh[c["source"]] += 1
        ambiguous[c["source"]] += bool(c.get("ambiguous"))
    out = [
        f"# Open-item digest: {today}",
        "",
        "Generated by workledger-kit's open-item-digest. Read-only: Linear was not consulted, so "
        "a new item "
        "here may already exist in Linear. Run syncing-open-items to dedup and submit.",
    ]
    if first_run:
        out.append("First run: every collected item is listed as new.")
    out += ["", "## Summary", "", "| Source | Collected | New | Ambiguous |", "|---|---|---|---|"]
    out += [
        f"| {label} | {collected[k]} | {fresh[k]} | {ambiguous[k]} |"
        for k, label in SOURCES.items()
    ]
    out += ["", "## New items"]
    for k, label in SOURCES.items():
        out += ["", f"### {label}"]
        items = [c for c in new if c["source"] == k]
        out += [
            f"- `{_line(c['source_ref']).replace('`', "'")}`: {_line(c['title'])} "
            f"({'needs a person' if c.get('ambiguous') else 'clear'})"
            + (f" <{_line(c['extra']['url'])}>" if (c.get("extra") or {}).get("url") else "")
            for c in items
        ] or ["- none"]
    out += ["", "## Sources that failed", ""]
    out += [f"- {f}" for f in failed] or ["- none"]
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    wlgr_paths.utf8_stdio()
    args = list(argv)
    first_run = "--first-run" in args
    if first_run:
        args.remove("--first-run")
    failed: list[str] = []
    if "--failed" in args:
        i = args.index("--failed")
        if i + 1 >= len(args):
            print(__doc__, file=sys.stderr)
            return 2
        failed = [x for x in args[i + 1].split(",") if x]
        del args[i : i + 2]
    if len(args) != 2 or any(f not in FAILABLE for f in failed):
        print(__doc__, file=sys.stderr)
        return 2
    try:
        import wlgr_config

        annotated = [
            c
            for n in args[0].split(",")
            for c in json.loads(wlgr_config.read_work(n))["candidates"]
        ]
        new = [c for n in args[1].split(",") for c in json.loads(wlgr_config.read_work(n))]
        text = build_digest(annotated, new, date.today().isoformat(), first_run, failed)
        folder = wlgr_config.workdir()
        n = 1
        while True:
            name = f"digest-{date.today().isoformat()}" + ("" if n == 1 else f"-{n}") + ".md"
            try:
                wlgr_paths.create_text(
                    folder / name, text
                )  # exclusive, no symlink follow: never overwrites
                break
            except FileExistsError:
                n += 1
    except (ValueError, OSError, KeyError, json.JSONDecodeError) as exc:
        print(f"wlgr_digest.py: {exc}", file=sys.stderr)
        return 1
    print(json.dumps({"written": name, "new": len(new), "collected": len(annotated)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
