name: 'Issue Opened Labeler'

on:
  issues:
    types:
      - 'opened'

concurrency:
  group: 'issue-opened-labeler-${{ github.event.issue.number }}'
  cancel-in-progress: true

permissions:
  issues: 'write'

jobs:
  label-issue:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
        with:
          persist-credentials: false
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            .github/actions/workflow-killswitch
            .github/actions/track-rerun
            .github/WORKFLOW_KILLSWITCH
      - name: 'Check Workflow Kill Switch'
        uses: ./.github/actions/workflow-killswitch
        with:
          killswitch-var: ${{ vars.WORKFLOW_KILLSWITCH }}

      - name: 'Track workflow rerun'
        if: github.run_attempt > 1
        uses: ./.github/actions/track-rerun

      - name: 'Generate GitHub App Token'
        id: 'generate_token'
        env:
          APP_ID: '${{ secrets.APP_ID }}'
        if: |-
          ${{ env.APP_ID != '' }}
        uses: 'actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b' # ratchet:actions/create-github-app-token@v2.1.1
        with:
          app-id: '${{ secrets.APP_ID }}'
          private-key: '${{ secrets.PRIVATE_KEY }}'

      - name: 'Add s: triage label'
        uses: 'actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3' # ratchet:actions/github-script@v9.0.0
        with:
          github-token: '${{ steps.generate_token.outputs.token || secrets.GITHUB_TOKEN }}'
          script: |-
            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const hasLabel = issue.labels.some(l => l.name === 's: triage');
            if (!hasLabel) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['s: triage']
              });
            } else {
              core.info('Issue already has s: triage label. Skipping.');
            }
